[project]
name = "Large-Scale-Design-and-Analysis-of-Neural-Networks_sharifware"
version = "0.0.1"
authors = [
  { name="Simon Cole", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/sharifware/Large-Scale-Design-and-Analysis-of-Neural-Networks"
Issues = "https://github.com/sharifware/Large-Scale-Design-and-Analysis-of-Neural-Networks/Issues"